name: nf-core Docker push (dev)
# This builds the docker image and pushes it to DockerHub
# Runs on nf-core repo releases and push event to 'dev' branch (PR merges)
on:
  workflow_dispatch
  #push:
  #  branches: [dev, issues/3466-gitpod]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (dev)
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    #if: ${{ github.repository == 'nf-core/tools' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build nfcore/tools:dev docker image
        run: docker build --no-cache . -t fljulian/nfcore-tools:dev

      - name: Build nfcore/devcontainer:dev devcontainer image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        with:
          configFile: .devcontainer/build-devcontainer/devcontainer.json
          imageName: fljulian/nfcore-devcontainer:dev
          platform: linux/amd64,linux/arm64
          push: false
          noCache: true

      - name: Push Docker images to DockerHub (dev)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push fljulian/nfcore-devcontainer:dev
          docker push fljulian/nfcore-tools:dev
